### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by zhang320** [mgonzs13/yolov8_ros#22]
Is this version of code unable to modify network structure and train?

**Comment by mgonzs13** [comment]
Hi @zhang320, you can train YOLOv8 as usual and then pass the new weights file to the launch file using the ```model``` parameter.

**Comment by zhang320** [comment]
If I want to modify the network structure, is this code not feasible

**Comment by zhang320** [comment]
Does it mean that I have to operate on the source code

**Comment by mgonzs13** [comment]
What do you have to change to make it work? This seems to be more related to Ultralytics. Have you checked issues like this https://github.com/ultralytics/ultralytics/issues/3194?

**Comment by zhang320** [comment]
ok, thank you
