### ISSUE TITLE
how can i convert 3d coordinate to real word coordinate?

### ISSUE THREAD

**Issue by cncowboy** [mgonzs13/yolov8_ros#23]
thanks for this pretty project, i can get 3d coordinate with launch file:yolov8_3d.launch.py, if i want to get the real world coordinate, how can i do it?

**Comment by mgonzs13** [comment]
The 3D positions are yet transformed to the target frame, by default to the base_link frame. Thus, you can change that target frame, for instance to the map or odom frame, resulting in 3D positions relative to the new frame. Is this what you are searching for?

**Comment by cncowboy** [comment]
got it, thanks!
