### ISSUE TITLE
No image in Rviz2 using realsense camera!

### ISSUE THREAD

**Issue by user-redans** [mgonzs13/yolov8_ros#35]
Hello,

I've tried to launch 'yolov8_bringup/yolov8.launch.py' but I have encountered an issue on Rviz2 yolo topic vizualization, see image below:
![10](https://github.com/mgonzs13/yolov8_ros/assets/35834736/a9fc211f-f311-422e-9603-67878e780662)
 
There is not any camera image from topic /yolo/dbg_image...You can see below a screenshoot with log terminal information:
![2](https://github.com/mgonzs13/yolov8_ros/assets/35834736/01d83204-2aa1-4f93-bb85-824d691d041c)
 
This is a list with all my ROS2-humble available topics:
![3](https://github.com/mgonzs13/yolov8_ros/assets/35834736/f8d30c4f-a4cf-45b5-9a58-be2b0a089d5c)

And some info's about my Jetson AGX Xavier that I'm using, with Jetpack 5.1.3: 
![4](https://github.com/mgonzs13/yolov8_ros/assets/35834736/79e0370c-ce76-4329-8b99-be559ab0b6d9)

I'm using a Intel RealSense camera, model D415.

I don't know what I'm missing? Do you have any suggestions?

**Comment by mgonzs13** [comment]
Hi @user-redans, which camera topic are you using? In your image, there are two topics. You may be publishing your realsense images in the ```/camera/camera/color/image_raw```and yolov8 is subscribed to the ```/camera/rgb/image_raw/ topic. Check also the QoS of the topics. You can modify both the image topic and the QoS using the launch params, take a look at the README.

**Comment by user-redans** [comment]
> Hi @user-redans, which camera topic are you using? In your image, there are two topics. You may be publishing your realsense images in the `/camera/camera/color/image_raw`and yolov8 is subscribed to the ```/camera/rgb/image_raw/ topic. Check also the QoS of the topics. You can modify both the image topic and the QoS using the launch params, take a look at the README.

I'm using default topic value, in launch .py script: "/camera/camera/color/image_raw" and image_reliability = 1

**Comment by user-redans** [comment]
Topic "/camera/rgb/image_raw/" vizualization is also wrong, see image below:
![11](https://github.com/mgonzs13/yolov8_ros/assets/35834736/9c9f72b6-127d-4a37-a6c3-bb0662a109a3)

**Comment by user-redans** [comment]
This is my graph with all nodes and topics(rqt_graph), see image below: 

![rqt1](https://github.com/mgonzs13/yolov8_ros/assets/35834736/8c39c564-a88e-4749-a544-1809ad252996)

**Comment by mgonzs13** [comment]
In the rqt_graph, you are using the topic /camera/rgb/image_raw instead of /camera/camera/color/image_raw. There are new changes in the repository; could you try to see if they work for you?

**Comment by user-redans** [comment]
It didn't work!
See my new graph:
![rqt3](https://github.com/mgonzs13/yolov8_ros/assets/35834736/6cac6416-bc77-4e1c-b06e-28b791b86a50)

**Comment by mgonzs13** [comment]
How are you launching it? It would be best if you were using something similar to this: ```ros2 launch yolov8_bringup yolov8.launch.py input_image_topic:=/camera/camera/color/image_raw image_reliability:=1```.

**Comment by user-redans** [comment]
I've launched with the same command line as you told me, but didn't work!
In Rviz2 only this topic "/camera/camera/color/image_raw" works, see image below:
![rviz10](https://github.com/mgonzs13/yolov8_ros/assets/35834736/767ca148-b50a-4682-9bc1-b3029bde7ff2)

I've used this command line for camera launching: ros2 launch realsense2_camera rs_launch.py

**Comment by mgonzs13** [comment]
Can you show me your rqt_graoh again after launching the command?

**Comment by mgonzs13** [comment]
Hi @user-redans, how is this going?
