### ISSUE TITLE
Encoding error by ultralytics prediction

### ISSUE THREAD

**Issue by SamuelHafner** [mgonzs13/yolov8_ros#39]
Hi @mgonzs13, 

thank you for your great work!!! 

I have an error when when running the yolov8_node the self.yolo.predict cause an error (tried on 2 different cameras):

[yolov8_node-1] RuntimeError: Given groups=1, weight of size [48, 3, 3, 3], expected input[1, 4, 384, 640] to have 3 channels, but got 4 channels instead

I could fix this after i changed the desired encoding on the cv2_bridge:
from: 
```python
self.cv_bridge.imgmsg_to_cv2(msg)
```
to 
```python
self.cv_bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
```

should we maybe add this permanent or is there some reason this encoding is empty?

**Comment by mgonzs13** [comment]
Hey @SamuelHafner, thanks for the issue. A better solution could be as follows. Can you try it?

```cv_image = self.cv_bridge.imgmsg_to_cv2(
                msg,
                desired_encoding=msg.encoding
            )```

**Comment by SamuelHafner** [comment]
Hey @mgonzs13, thanks for your fast response. It is also not working because in my case I have an image with the encoding `bgra8` and therefore an cv_image  shape of `(360, 640, 4)`. We have the alpha value too, 

If I change the desired encoding for the image to `bgr8` it converts the cv_image with the shape `(360, 480, 3)`.

And I think that the yolo package can only handle images without alpha

**Comment by mgonzs13** [comment]
If you don't want to modify yolov8_ros, you can try to add a node to remove the alpha channel and republish the image as bgr8.

**Comment by SamuelHafner** [comment]
Yeah i could. But I added this desired_endcoding permanent now.
Would you like this change too? Should I do an merge request or just let it local. 
Because normally you always would need an bgr8 encoding. 

Btw. these recordings are from robocup@home 2023 right? We also were there. Which team? :)

**Comment by kylenietfeld** [comment]
For me, I was using ros-gst-bridge and I simply added the line: "! video/x-raw,format=BGR" to my pipeline so the image being published was bgr format instead of bgra. Then yolo worked as expected.
