### ISSUE TITLE
how to see 3d bbox in rviz2

### ISSUE THREAD

**Issue by weilinhan** [mgonzs13/yolov8_ros#50]
Hello everyone, I am a newbie using RVIZ2, I ran the 3D model according to the instructions of the tutorial（$ ros2 launch yolov8_bringup yolov8_3d.launch.py model:=yolov8m-pose.pt ）and then on the RVIZ2 I can see the 2D detection box, how can I see the 3D detection box like the tutorial in rviz2

**Comment by mgonzs13** [comment]
Hey @weilinhan, you have to use the markers in rviz2. Then, you will get 3D markers as spheres in the 3D viewer of rviz2.
