### ISSUE TITLE
Run YOlo8 in ROS

### ISSUE THREAD

**Issue by golnazhabibi3** [mgonzs13/yolov8_ros#8]
Hi,

Can we run this wrapper in ROS?

Thanks,
Golnaz

**Comment by mgonzs13** [comment]
This wrapper is available for ROS 2 Humble. Do you mean ROS 1?

**Comment by golnazhabibi3** [comment]
Yes, I mean ROS1. I am using ROS Melodic and wonder which Yolo version is available and compatible with that.

Thanks.

**Comment by mgonzs13** [comment]
I don't have plans on developing a version for ROS 1. There should be more wrappers for YOLO in ROS, for instance [Darknet](https://github.com/leggedrobotics/darknet_ros) which is YOLOv3. Btw, I recommend you to migrate to Noetic or ROS 2 Humble since Melodic EOL was on April.
