### ISSUE TITLE
[debug_node-3] AttributeError: module 'cv2' has no attribute 'Mat'

### ISSUE THREAD

**Issue by mzahana** [mgonzs13/yolov8_ros#9]
Hi @mgonzs13 
Thanks for the great repo.

I am using your latest main branch inside a docker container on Jetson Orin Nx with Ros2 container.

My Opncv version is `4.5.0`

The `debug_node` throws the following error.

`[debug_node-3] AttributeError: module 'cv2' has no attribute 'Mat'`

Any idea what could be the issue ?

**Comment by mgonzs13** [comment]
Hi @mzahana, I am using OpenCV 4.5.4 and opencv-python 4.8.0.76. Verify your opencv-python version, upgrading might be necessary.

**Comment by raniaa03** [comment]
I am running into the same issue and have opencv-python 4.8.0.76 installed. Was there a fix found?

**Comment by mgonzs13** [comment]
I have replaced cv2.Mat with np.array. This should solve it.
